stages:
  - build
  - deploy

before_script:
  - docker info

after_script:
  - docker container prune -f
  - docker image prune -f

build_image:
  stage: build
  only:
    - production
  script:
    - docker compose -f docker-compose.prod.yaml build

deploy_image:
  stage: deploy
  only:
    - production
  script:
    - docker compose -f docker-compose.prod.yaml up -d
