services:
  open-webui:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - /home/helliwood/.env/.plattform
    container_name: helliwood-platform
    volumes:
      - helliwood-platform:/app/backend/data
    ports:
      - 4000:8080
    extra_hosts:
      - host.docker.internal:host-gateway
    restart: unless-stopped

volumes:
  helliwood-platform:
